Algoritmo "ex1"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
nome: caracter

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("qual seu nome ", nome)
leia(nome)
escreva("seja bem vindo ", nome)

Fimalgoritmo