Algoritmo "semnome"
// Disciplina  : Lógica de Programação
// Professor   : André Olímpio 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 13/02/2026
Var
// Seção de Declarações das variáveis 
numero: inteiro
resto: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("seu numero")
leia(numero)
resto <- numero mod 2
escreva("resto é ", resto)

Fimalgoritmo